# Generated by Django 5.1.1 on 2025-01-14 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz_question_answers',
            old_name='answer1',
            new_name='answer',
        ),
        migrations.RemoveField(
            model_name='quiz_question_answers',
            name='answer2',
        ),
        migrations.RemoveField(
            model_name='quiz_question_answers',
            name='answer3',
        ),
    ]
