# Generated by Django 5.1.1 on 2025-01-20 10:54

import app_quiz.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0002_rename_answer1_quiz_question_answers_answer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz_question',
            name='image_quest',
            field=models.ImageField(blank=True, null=True, upload_to=app_quiz.models.quiz_image_upload_path_for_question),
        ),
        migrations.AlterField(
            model_name='quiz_title',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=app_quiz.models.quiz_image_upload_path_for_quiz),
        ),
    ]
