# Generated by Django 5.0.7 on 2025-02-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_quiz', '0003_alter_quiz_question_image_quest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz_question_answers',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
